### ISSUE TITLE
Support For Shared Devices

### ISSUE THREAD

**Issue by ssmoss** [mpatfield/homebridge-flume#40]
It seems that the plugin will not load shared Flume devices. Is it possible to support shared devices? When I sign into the portal page I can see the data for the device. Thanks.

**Comment by ssmoss** [comment]
I created a pull request to load shared devices as well as primary devices for the account https://github.com/bwp91/homebridge-flume/pull/42

I see you have a method to pull usage data, can HomeKit display that?

**Comment by bwp91** [comment]
Thanks! this is included in new beta version 2.1.0-beta.0, will make a release of this soon!

**Comment by ssmoss** [comment]
@bwp91 Happy to help and thanks so much for including it. Will the plugin expose more than leak detection in the future or is that all that is allowed in HomeKit?

**Comment by bwp91** [comment]
honestly, i don’t know!

truth is, i don’t actually own a flume device.

i created this plugin a while back from a request and i think also because an existing plugin wasn’t working properly, so i don’t develop this plugin as much as i do my other plugins where i actually own devices. 

i think i have some extra information that is available in the Eve homekit app.

what other stuff were you looking for?

if you are up for it, please feel free to create any PR to enhance plugin!

**Comment by ssmoss** [comment]
@bwp91 I know very little about HomeKit and what can be exposed for the device. I was able to make that PR to add the shared device which seemed to make the leak detector show up for me. I saw there was a query in there to pull daily, current month, and previous months data but I don't see that anywhere in HomeKit.

**Comment by bwp91** [comment]
The Home app is very limited to what it can display. There are some extra values that can be seen in the Eve HomeKit app - dunno if you have this? it’s basically a _better_ home app!

**Comment by ssmoss** [comment]
Ah, I will install that a take a look to see if more is exposed. I guess at the end of the day if Home tells me there is a leak that is all I really care about.

**Comment by bwp91** [comment]
Should be included as part of new version of plugin :)

Thanks again for your time on this
